language: erlang
sudo: false
otp_release:
  - 20.0
  - 19.3
  - 18.3
  - 17.5
  - R16B03-1
install: true
script:
  - ./rebar3 compile 
  - ./rebar3 eunit
  - ./rebar3 xref
# maps support breaks edoc generation
# TODO reinstate edoc generation with
# jsn 2.0.0
#  - ./rebar3 edoc
